package pa2;

// Import declarations generated by the SALSA compiler, do not modify.
import java.io.IOException;
import java.util.Vector;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.InvocationTargetException;

import salsa.language.Actor;
import salsa.language.ActorReference;
import salsa.language.Message;
import salsa.language.RunTime;
import salsa.language.ServiceFactory;
import gc.WeakReference;
import salsa.language.Token;
import salsa.language.exceptions.*;
import salsa.language.exceptions.CurrentContinuationException;

import salsa.language.UniversalActor;

import salsa.naming.UAN;
import salsa.naming.UAL;
import salsa.naming.MalformedUALException;
import salsa.naming.MalformedUANException;

import salsa.resources.SystemService;

import salsa.resources.ActorService;

// End SALSA compiler generated import delcarations.

import salsa.language.ActorReference;

public class Coordinator extends UniversalActor  {
	public static void main(String args[]) {
		UAN uan = null;
		UAL ual = null;
		if (System.getProperty("uan") != null) {
			uan = new UAN( System.getProperty("uan") );
			ServiceFactory.getTheater();
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("ual") != null) {
			ual = new UAL( System.getProperty("ual") );

			if (uan == null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an actor to have a ual at runtime without a uan.");
				System.err.println("	To give an actor a specific ual at runtime, use the identifier system property.");
				System.exit(0);
			}
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("identifier") != null) {
			if (ual != null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an identifier and a ual with system properties when creating an actor.");
				System.exit(0);
			}
			ual = new UAL( ServiceFactory.getTheater().getLocation() + System.getProperty("identifier"));
		}
		RunTime.receivedMessage();
		Coordinator instance = (Coordinator)new Coordinator(uan, ual,null).construct();
		gc.WeakReference instanceRef=new gc.WeakReference(uan,ual);
		{
			Object[] _arguments = { args };

			//preAct() for local actor creation
			//act() for remote actor creation
			if (ual != null && !ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {instance.send( new Message(instanceRef, instanceRef, "act", _arguments, false) );}
			else {instance.send( new Message(instanceRef, instanceRef, "preAct", _arguments, false) );}
		}
		RunTime.finishedProcessingMessage();
	}

	public static ActorReference getReferenceByName(UAN uan)	{ return new Coordinator(false, uan); }
	public static ActorReference getReferenceByName(String uan)	{ return Coordinator.getReferenceByName(new UAN(uan)); }
	public static ActorReference getReferenceByLocation(UAL ual)	{ return new Coordinator(false, ual); }

	public static ActorReference getReferenceByLocation(String ual)	{ return Coordinator.getReferenceByLocation(new UAL(ual)); }
	public Coordinator(boolean o, UAN __uan)	{ super(false,__uan); }
	public Coordinator(boolean o, UAL __ual)	{ super(false,__ual); }
	public Coordinator(UAN __uan,UniversalActor.State sourceActor)	{ this(__uan, null, sourceActor); }
	public Coordinator(UAL __ual,UniversalActor.State sourceActor)	{ this(null, __ual, sourceActor); }
	public Coordinator(UniversalActor.State sourceActor)		{ this(null, null, sourceActor);  }
	public Coordinator()		{  }
	public Coordinator(UAN __uan, UAL __ual, Object obj) {
		//decide the type of sourceActor
		//if obj is null, the actor must be the startup actor.
		//if obj is an actorReference, this actor is created by a remote actor

		if (obj instanceof UniversalActor.State || obj==null) {
			  UniversalActor.State sourceActor;
			  if (obj!=null) { sourceActor=(UniversalActor.State) obj;}
			  else {sourceActor=null;}

			  //remote creation message sent to a remote system service.
			  if (__ual != null && !__ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {
			    WeakReference sourceRef;
			    if (sourceActor!=null && sourceActor.getUAL() != null) {sourceRef = new WeakReference(sourceActor.getUAN(),sourceActor.getUAL());}
			    else {sourceRef = null;}
			    if (sourceActor != null) {
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual!=null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());
			      activateGC();
			    }
			    createRemotely(__uan, __ual, "pa2.Coordinator", sourceRef);
			  }

			  // local creation
			  else {
			    State state = new State(__uan, __ual);

			    //assume the reference is weak
			    muteGC();

			    //the source actor is  the startup actor
			    if (sourceActor == null) {
			      state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			    }

			    //the souce actor is a normal actor
			    else if (sourceActor instanceof UniversalActor.State) {

			      // this reference is part of garbage collection
			      activateGC();

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());

			      /* Garbage collection registration:
			       * register 'this reference' in sourceActor's forward list @
			       * register 'this reference' in the forward acquaintance's inverse list
			       */
			      String inverseRefString=null;
			      if (sourceActor.getUAN()!=null) {inverseRefString=sourceActor.getUAN().toString();}
			      else if (sourceActor.getUAL()!=null) {inverseRefString=sourceActor.getUAL().toString();}
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual != null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}
			      else {sourceActor.getActorMemory().getForwardList().putReference(state.getUAL());}

			      //put the inverse reference information in the actormemory
			      if (inverseRefString!=null) state.getActorMemory().getInverseList().putInverseReference(inverseRefString);
			    }
			    state.updateSelf(this);
			    ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(), state);
			    if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
			  }
		}

		//creation invoked by a remote message
		else if (obj instanceof ActorReference) {
			  ActorReference sourceRef= (ActorReference) obj;
			  State state = new State(__uan, __ual);
			  muteGC();
			  state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			  if (sourceRef.getUAN() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAN());}
			  else if (sourceRef.getUAL() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAL());}
			  state.updateSelf(this);
			  ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(),state);
			  if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
		}
	}

	public UniversalActor construct() {
		Object[] __arguments = { };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public class State extends UniversalActor .State {
		public Coordinator self;
		public void updateSelf(ActorReference actorReference) {
			((Coordinator)actorReference).setUAL(getUAL());
			((Coordinator)actorReference).setUAN(getUAN());
			self = new Coordinator(false,getUAL());
			self.setUAN(getUAN());
			self.setUAL(getUAL());
			self.activateGC();
		}

		public State() {
			this(null, null);
		}

		public State(UAN __uan, UAL __ual) {
			super(__uan, __ual);
			addClassName( "pa2.Coordinator$State" );
			addMethodsForClasses();
		}

		public void construct() {}

		public void process(Message message) {
			Method[] matches = getMatches(message.getMethodName());
			Object returnValue = null;
			Exception exception = null;

			if (matches != null) {
				if (!message.getMethodName().equals("die")) {activateArgsGC(message);}
				for (int i = 0; i < matches.length; i++) {
					try {
						if (matches[i].getParameterTypes().length != message.getArguments().length) continue;
						returnValue = matches[i].invoke(this, message.getArguments());
					} catch (Exception e) {
						if (e.getCause() instanceof CurrentContinuationException) {
							sendGeneratedMessages();
							return;
						} else if (e instanceof InvocationTargetException) {
							sendGeneratedMessages();
							exception = (Exception)e.getCause();
							break;
						} else {
							continue;
						}
					}
					sendGeneratedMessages();
					currentMessage.resolveContinuations(returnValue);
					return;
				}
			}

			System.err.println("Message processing exception:");
			if (message.getSource() != null) {
				System.err.println("\tSent by: " + message.getSource().toString());
			} else System.err.println("\tSent by: unknown");
			System.err.println("\tReceived by actor: " + toString());
			System.err.println("\tMessage: " + message.toString());
			if (exception == null) {
				if (matches == null) {
					System.err.println("\tNo methods with the same name found.");
					return;
				}
				System.err.println("\tDid not match any of the following: ");
				for (int i = 0; i < matches.length; i++) {
					System.err.print("\t\tMethod: " + matches[i].getName() + "( ");
					Class[] parTypes = matches[i].getParameterTypes();
					for (int j = 0; j < parTypes.length; j++) {
						System.err.print(parTypes[j].getName() + " ");
					}
					System.err.println(")");
				}
			} else {
				System.err.println("\tThrew exception: " + exception);
				exception.printStackTrace();
			}
		}

		ActorReference replyRef;
		double d1Best;
		java.util.ArrayList d1Pairs;
		int d1Expected;
		int d1Received;
		double d2Best;
		java.util.ArrayList d2Rows;
		int d2Expected;
		int d2Received;
		double t3Best;
		java.util.ArrayList t3Rows;
		int t3Expected;
		int t3Received;
		java.util.ArrayList theaterBases;
		int rr;
		public void loadTheatersFromEnv() {
			theaterBases = new java.util.ArrayList();
			rr = 0;
			try {
				String env = java.lang.System.getenv("WORKER_THEATERS");
				if (env==null) {				return;
}				env = env.trim();
				if (env.length()==0) {				return;
}				String[] parts = env.split(",");
				for (int i = 0; i<parts.length; i++){
					String b = parts[i].trim();
					if (b.length()==0) {continue;}					if (!b.endsWith("/UAL/")) {{
						if (!b.endsWith("/")) {b = b+"/";
}						b = b+"UAL/";
					}
}					theaterBases.add(b);
				}
			}
			catch (Exception __e) {
			}

		}
		public salsa.naming.UAL pickWorkerUAL(String tag) {
			if (theaterBases==null||theaterBases.size()==0) {			return null;
}			String base = (String)theaterBases.get(rr%theaterBases.size());
			rr++;
			String id = tag+"-"+java.lang.System.currentTimeMillis()+"-"+rr;
			return new salsa.naming.UAL(base+id);
		}
		public void computeClosest(java.util.ArrayList flights, salsa.naming.UAL replyUAL) {
			this.replyRef = pa2.Main.getReferenceByLocation(replyUAL);
			this.d1Best = java.lang.Double.POSITIVE_INFINITY;
			this.d1Pairs = new java.util.ArrayList();
			this.d1Received = 0;
			{
				// loadTheatersFromEnv()
				{
					Object _arguments[] = {  };
					Message message = new Message( self, self, "loadTheatersFromEnv", _arguments, null, null );
					__messages.add( message );
				}
			}
			int n = flights.size();
			if (n<2) {{
				{
					// replyRef<-afterClosest(java.lang.Double.NaN, d1Pairs)
					{
						Object _arguments[] = { java.lang.Double.NaN, d1Pairs };
						Message message = new Message( self, replyRef, "afterClosest", _arguments, null, null );
						__messages.add( message );
					}
				}
				return;
			}
}			int workers = 4;
			if (n<100) {workers = java.lang.Math.min(2, n);
}			int chunk = (n+workers-1)/workers;
			d1Expected = 0;
			for (int w = 0; w<workers; w++){
				int iStart = w*chunk;
				int iEnd = java.lang.Math.min(n-2, (w+1)*chunk-1);
				if (iStart>=n-1) {break;}				salsa.naming.UAL ual = pickWorkerUAL("pair");
				if (ual==null) {{
					PairWorker pw = ((PairWorker)new PairWorker(this).construct());
					d1Expected++;
					{
						// pw<-findMinPairs(flights, iStart, iEnd, this.getUAL())
						{
							Object _arguments[] = { flights, iStart, iEnd, this.getUAL() };
							Message message = new Message( self, pw, "findMinPairs", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}				else {{
					ActorReference pw = pa2.PairWorker.getReferenceByLocation(ual);
					d1Expected++;
					{
						// pw<-findMinPairs(flights, iStart, iEnd, this.getUAL())
						{
							Object _arguments[] = { flights, iStart, iEnd, this.getUAL() };
							Message message = new Message( self, pw, "findMinPairs", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}			}
		}
		public void report(double best, java.util.ArrayList pairs) {
			d1Received++;
			if (best<d1Best-1e-9) {{
				d1Best = best;
				d1Pairs = pairs;
			}
}			else {if (java.lang.Math.abs(best-d1Best)<=1e-9) {{
				java.util.HashSet seen = new java.util.HashSet(d1Pairs);
				java.util.Iterator it = pairs.iterator();
				while (it.hasNext()) {
					Object s = it.next();
					if (!seen.contains(s)) {{
						d1Pairs.add(s);
						seen.add(s);
					}
}				}
			}
}}			if (d1Received==d1Expected) {			{
				// replyRef<-afterClosest(d1Best, d1Pairs)
				{
					Object _arguments[] = { d1Best, d1Pairs };
					Message message = new Message( self, replyRef, "afterClosest", _arguments, null, null );
					__messages.add( message );
				}
			}
}		}
		public void computeDcpa(java.util.ArrayList flights, salsa.naming.UAL replyUAL) {
			this.replyRef = pa2.Main.getReferenceByLocation(replyUAL);
			this.d2Best = java.lang.Double.POSITIVE_INFINITY;
			this.d2Rows = new java.util.ArrayList();
			this.d2Received = 0;
			int n = flights.size();
			if (n<2) {{
				{
					// replyRef<-afterDcpa(java.lang.Double.NaN, d2Rows)
					{
						Object _arguments[] = { java.lang.Double.NaN, d2Rows };
						Message message = new Message( self, replyRef, "afterDcpa", _arguments, null, null );
						__messages.add( message );
					}
				}
				return;
			}
}			int workers = 4;
			if (n<100) {workers = java.lang.Math.min(2, n);
}			int chunk = (n+workers-1)/workers;
			d2Expected = 0;
			for (int w = 0; w<workers; w++){
				int iStart = w*chunk;
				int iEnd = java.lang.Math.min(n-2, (w+1)*chunk-1);
				if (iStart>=n-1) {break;}				salsa.naming.UAL ual = pickWorkerUAL("dcpa");
				if (ual==null) {{
					DcpaWorker wk = ((DcpaWorker)new DcpaWorker(this).construct());
					d2Expected++;
					{
						// wk<-findMinDcpa(flights, iStart, iEnd, this.getUAL())
						{
							Object _arguments[] = { flights, iStart, iEnd, this.getUAL() };
							Message message = new Message( self, wk, "findMinDcpa", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}				else {{
					ActorReference wk = pa2.DcpaWorker.getReferenceByLocation(ual);
					d2Expected++;
					{
						// wk<-findMinDcpa(flights, iStart, iEnd, this.getUAL())
						{
							Object _arguments[] = { flights, iStart, iEnd, this.getUAL() };
							Message message = new Message( self, wk, "findMinDcpa", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}			}
		}
		public void reportDcpa(double best, java.util.ArrayList rows) {
			d2Received++;
			if (best<d2Best-1e-9) {{
				d2Best = best;
				d2Rows = rows;
			}
}			else {if (java.lang.Math.abs(best-d2Best)<=1e-9) {{
				java.util.Iterator it = rows.iterator();
				while (it.hasNext()) d2Rows.add(it.next());
			}
}}			if (d2Received==d2Expected) {			{
				// replyRef<-afterDcpa(d2Best, d2Rows)
				{
					Object _arguments[] = { d2Best, d2Rows };
					Message message = new Message( self, replyRef, "afterDcpa", _arguments, null, null );
					__messages.add( message );
				}
			}
}		}
		public void computeTcpa(java.util.ArrayList flights, salsa.naming.UAL replyUAL) {
			this.replyRef = pa2.Main.getReferenceByLocation(replyUAL);
			this.t3Best = java.lang.Double.POSITIVE_INFINITY;
			this.t3Rows = new java.util.ArrayList();
			this.t3Received = 0;
			int n = flights.size();
			int workers = 4;
			if (n<100) {workers = java.lang.Math.min(2, n);
}			int chunk = (n+workers-1)/workers;
			t3Expected = 0;
			for (int w = 0; w<workers; w++){
				int iStart = w*chunk;
				int iEnd = java.lang.Math.min(n-2, (w+1)*chunk-1);
				if (iStart>=n-1) {break;}				salsa.naming.UAL ual = pickWorkerUAL("tcpa");
				if (ual==null) {{
					TcpaWorker wk = ((TcpaWorker)new TcpaWorker(this).construct());
					t3Expected++;
					{
						// wk<-findSoonestTcpa(flights, iStart, iEnd, this.getUAL())
						{
							Object _arguments[] = { flights, iStart, iEnd, this.getUAL() };
							Message message = new Message( self, wk, "findSoonestTcpa", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}				else {{
					ActorReference wk = pa2.TcpaWorker.getReferenceByLocation(ual);
					t3Expected++;
					{
						// wk<-findSoonestTcpa(flights, iStart, iEnd, this.getUAL())
						{
							Object _arguments[] = { flights, iStart, iEnd, this.getUAL() };
							Message message = new Message( self, wk, "findSoonestTcpa", _arguments, null, null );
							__messages.add( message );
						}
					}
				}
}			}
		}
		public void reportTcpa(double bestT, java.util.ArrayList rows) {
			t3Received++;
			if (bestT<t3Best-1e-9) {{
				t3Best = bestT;
				t3Rows = rows;
			}
}			else {if (java.lang.Math.abs(bestT-t3Best)<=1e-9) {{
				java.util.Iterator it = rows.iterator();
				while (it.hasNext()) t3Rows.add(it.next());
			}
}}			if (t3Received==t3Expected) {			{
				// replyRef<-afterTcpa(t3Best, t3Rows)
				{
					Object _arguments[] = { t3Best, t3Rows };
					Message message = new Message( self, replyRef, "afterTcpa", _arguments, null, null );
					__messages.add( message );
				}
			}
}		}
	}
}