package pa2;

// Import declarations generated by the SALSA compiler, do not modify.
import java.io.IOException;
import java.util.Vector;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.lang.reflect.InvocationTargetException;

import salsa.language.Actor;
import salsa.language.ActorReference;
import salsa.language.Message;
import salsa.language.RunTime;
import salsa.language.ServiceFactory;
import gc.WeakReference;
import salsa.language.Token;
import salsa.language.exceptions.*;
import salsa.language.exceptions.CurrentContinuationException;

import salsa.language.UniversalActor;

import salsa.naming.UAN;
import salsa.naming.UAL;
import salsa.naming.MalformedUALException;
import salsa.naming.MalformedUANException;

import salsa.resources.SystemService;

import salsa.resources.ActorService;

// End SALSA compiler generated import delcarations.

import pa2.Flight;
import pa2.Kinematics;

public class DcpaWorker extends UniversalActor  {
	public static void main(String args[]) {
		UAN uan = null;
		UAL ual = null;
		if (System.getProperty("uan") != null) {
			uan = new UAN( System.getProperty("uan") );
			ServiceFactory.getTheater();
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("ual") != null) {
			ual = new UAL( System.getProperty("ual") );

			if (uan == null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an actor to have a ual at runtime without a uan.");
				System.err.println("	To give an actor a specific ual at runtime, use the identifier system property.");
				System.exit(0);
			}
			RunTime.receivedUniversalActor();
		}
		if (System.getProperty("identifier") != null) {
			if (ual != null) {
				System.err.println("Actor Creation Error:");
				System.err.println("	uan: " + uan);
				System.err.println("	ual: " + ual);
				System.err.println("	Identifier: " + System.getProperty("identifier"));
				System.err.println("	Cannot specify an identifier and a ual with system properties when creating an actor.");
				System.exit(0);
			}
			ual = new UAL( ServiceFactory.getTheater().getLocation() + System.getProperty("identifier"));
		}
		RunTime.receivedMessage();
		DcpaWorker instance = (DcpaWorker)new DcpaWorker(uan, ual,null).construct();
		gc.WeakReference instanceRef=new gc.WeakReference(uan,ual);
		{
			Object[] _arguments = { args };

			//preAct() for local actor creation
			//act() for remote actor creation
			if (ual != null && !ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {instance.send( new Message(instanceRef, instanceRef, "act", _arguments, false) );}
			else {instance.send( new Message(instanceRef, instanceRef, "preAct", _arguments, false) );}
		}
		RunTime.finishedProcessingMessage();
	}

	public static ActorReference getReferenceByName(UAN uan)	{ return new DcpaWorker(false, uan); }
	public static ActorReference getReferenceByName(String uan)	{ return DcpaWorker.getReferenceByName(new UAN(uan)); }
	public static ActorReference getReferenceByLocation(UAL ual)	{ return new DcpaWorker(false, ual); }

	public static ActorReference getReferenceByLocation(String ual)	{ return DcpaWorker.getReferenceByLocation(new UAL(ual)); }
	public DcpaWorker(boolean o, UAN __uan)	{ super(false,__uan); }
	public DcpaWorker(boolean o, UAL __ual)	{ super(false,__ual); }
	public DcpaWorker(UAN __uan,UniversalActor.State sourceActor)	{ this(__uan, null, sourceActor); }
	public DcpaWorker(UAL __ual,UniversalActor.State sourceActor)	{ this(null, __ual, sourceActor); }
	public DcpaWorker(UniversalActor.State sourceActor)		{ this(null, null, sourceActor);  }
	public DcpaWorker()		{  }
	public DcpaWorker(UAN __uan, UAL __ual, Object obj) {
		//decide the type of sourceActor
		//if obj is null, the actor must be the startup actor.
		//if obj is an actorReference, this actor is created by a remote actor

		if (obj instanceof UniversalActor.State || obj==null) {
			  UniversalActor.State sourceActor;
			  if (obj!=null) { sourceActor=(UniversalActor.State) obj;}
			  else {sourceActor=null;}

			  //remote creation message sent to a remote system service.
			  if (__ual != null && !__ual.getLocation().equals(ServiceFactory.getTheater().getLocation())) {
			    WeakReference sourceRef;
			    if (sourceActor!=null && sourceActor.getUAL() != null) {sourceRef = new WeakReference(sourceActor.getUAN(),sourceActor.getUAL());}
			    else {sourceRef = null;}
			    if (sourceActor != null) {
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual!=null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());
			      activateGC();
			    }
			    createRemotely(__uan, __ual, "pa2.DcpaWorker", sourceRef);
			  }

			  // local creation
			  else {
			    State state = new State(__uan, __ual);

			    //assume the reference is weak
			    muteGC();

			    //the source actor is  the startup actor
			    if (sourceActor == null) {
			      state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			    }

			    //the souce actor is a normal actor
			    else if (sourceActor instanceof UniversalActor.State) {

			      // this reference is part of garbage collection
			      activateGC();

			      //update the source of this actor reference
			      setSource(sourceActor.getUAN(), sourceActor.getUAL());

			      /* Garbage collection registration:
			       * register 'this reference' in sourceActor's forward list @
			       * register 'this reference' in the forward acquaintance's inverse list
			       */
			      String inverseRefString=null;
			      if (sourceActor.getUAN()!=null) {inverseRefString=sourceActor.getUAN().toString();}
			      else if (sourceActor.getUAL()!=null) {inverseRefString=sourceActor.getUAL().toString();}
			      if (__uan != null) {sourceActor.getActorMemory().getForwardList().putReference(__uan);}
			      else if (__ual != null) {sourceActor.getActorMemory().getForwardList().putReference(__ual);}
			      else {sourceActor.getActorMemory().getForwardList().putReference(state.getUAL());}

			      //put the inverse reference information in the actormemory
			      if (inverseRefString!=null) state.getActorMemory().getInverseList().putInverseReference(inverseRefString);
			    }
			    state.updateSelf(this);
			    ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(), state);
			    if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
			  }
		}

		//creation invoked by a remote message
		else if (obj instanceof ActorReference) {
			  ActorReference sourceRef= (ActorReference) obj;
			  State state = new State(__uan, __ual);
			  muteGC();
			  state.getActorMemory().getInverseList().putInverseReference("rmsp://me");
			  if (sourceRef.getUAN() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAN());}
			  else if (sourceRef.getUAL() != null) {state.getActorMemory().getInverseList().putInverseReference(sourceRef.getUAL());}
			  state.updateSelf(this);
			  ServiceFactory.getNaming().setEntry(state.getUAN(), state.getUAL(),state);
			  if (getUAN() != null) ServiceFactory.getNaming().update(state.getUAN(), state.getUAL());
		}
	}

	public UniversalActor construct() {
		Object[] __arguments = { };
		this.send( new Message(this, this, "construct", __arguments, null, null) );
		return this;
	}

	public class State extends UniversalActor .State {
		public DcpaWorker self;
		public void updateSelf(ActorReference actorReference) {
			((DcpaWorker)actorReference).setUAL(getUAL());
			((DcpaWorker)actorReference).setUAN(getUAN());
			self = new DcpaWorker(false,getUAL());
			self.setUAN(getUAN());
			self.setUAL(getUAL());
			self.activateGC();
		}

		public State() {
			this(null, null);
		}

		public State(UAN __uan, UAL __ual) {
			super(__uan, __ual);
			addClassName( "pa2.DcpaWorker$State" );
			addMethodsForClasses();
		}

		public void construct() {}

		public void process(Message message) {
			Method[] matches = getMatches(message.getMethodName());
			Object returnValue = null;
			Exception exception = null;

			if (matches != null) {
				if (!message.getMethodName().equals("die")) {activateArgsGC(message);}
				for (int i = 0; i < matches.length; i++) {
					try {
						if (matches[i].getParameterTypes().length != message.getArguments().length) continue;
						returnValue = matches[i].invoke(this, message.getArguments());
					} catch (Exception e) {
						if (e.getCause() instanceof CurrentContinuationException) {
							sendGeneratedMessages();
							return;
						} else if (e instanceof InvocationTargetException) {
							sendGeneratedMessages();
							exception = (Exception)e.getCause();
							break;
						} else {
							continue;
						}
					}
					sendGeneratedMessages();
					currentMessage.resolveContinuations(returnValue);
					return;
				}
			}

			System.err.println("Message processing exception:");
			if (message.getSource() != null) {
				System.err.println("\tSent by: " + message.getSource().toString());
			} else System.err.println("\tSent by: unknown");
			System.err.println("\tReceived by actor: " + toString());
			System.err.println("\tMessage: " + message.toString());
			if (exception == null) {
				if (matches == null) {
					System.err.println("\tNo methods with the same name found.");
					return;
				}
				System.err.println("\tDid not match any of the following: ");
				for (int i = 0; i < matches.length; i++) {
					System.err.print("\t\tMethod: " + matches[i].getName() + "( ");
					Class[] parTypes = matches[i].getParameterTypes();
					for (int j = 0; j < parTypes.length; j++) {
						System.err.print(parTypes[j].getName() + " ");
					}
					System.err.println(")");
				}
			} else {
				System.err.println("\tThrew exception: " + exception);
				exception.printStackTrace();
			}
		}

		public void findMinDcpa(java.util.ArrayList flights, java.lang.Integer iStartObj, java.lang.Integer iEndObj, salsa.naming.UAL parentUAL) {
			int iStart = iStartObj.intValue();
			int iEnd = iEndObj.intValue();
			double best = java.lang.Double.POSITIVE_INFINITY;
			java.util.ArrayList rows = new java.util.ArrayList();
			int n = flights.size();
			for (int i = iStart; i<=iEnd&&i<n-1; i++){
				Flight a = (Flight)flights.get(i);
				for (int j = i+1; j<n; j++){
					Flight b = (Flight)flights.get(j);
					double[] dEN = Kinematics.deltaEN_Nmi(a.latDeg, a.lonDeg, b.latDeg, b.lonDeg);
					double dE0 = dEN[0], dN0 = dEN[1];
					double dZ0 = Kinematics.feetToNmi(b.altFt-a.altFt);
					double[] vA = Kinematics.velocityEN_NmiPerSec(a.trackDeg, a.hsKnots);
					double[] vB = Kinematics.velocityEN_NmiPerSec(b.trackDeg, b.hsKnots);
					double vE = vB[0]-vA[0];
					double vN = vB[1]-vA[1];
					double vZ = Kinematics.feetToNmi((b.vsFpm-a.vsFpm)/60.0);
					double rv = dE0*vE+dN0*vN+dZ0*vZ;
					double vv = vE*vE+vN*vN+vZ*vZ;
					double t = 0.0;
					if (vv>0) {{
						t = -rv/vv;
						if (t<0) {t = 0;
}					}
}					double dE = dE0+vE*t;
					double dN = dN0+vN*t;
					double dZ = dZ0+vZ*t;
					double dcpa = java.lang.Math.sqrt(dE*dE+dN*dN+dZ*dZ);
					if (dcpa<best-1e-9) {{
						best = dcpa;
						rows.clear();
						rows.add(formatRowAtTime(a, b, t));
					}
}					else {if (java.lang.Math.abs(dcpa-best)<=1e-9) {{
						rows.add(formatRowAtTime(a, b, t));
					}
}}				}
			}
			salsa.language.ActorReference parent = pa2.Coordinator.getReferenceByLocation(parentUAL);
			{
				// parent<-reportDcpa(best, rows)
				{
					Object _arguments[] = { best, rows };
					Message message = new Message( self, parent, "reportDcpa", _arguments, null, null );
					__messages.add( message );
				}
			}
		}
		public String formatRowAtTime(Flight a, Flight b, double tsec) {
			double distA = a.hsKnots/3600.0*tsec;
			double distB = b.hsKnots/3600.0*tsec;
			double[] A = Kinematics.moveAlong(a.latDeg, a.lonDeg, a.trackDeg, distA);
			double[] B = Kinematics.moveAlong(b.latDeg, b.lonDeg, b.trackDeg, distB);
			double altA = a.altFt+a.vsFpm*(tsec/60.0);
			double altB = b.altFt+b.vsFpm*(tsec/60.0);
			return a.id+" "+String.format(java.util.Locale.US, "%.6f %.6f %.0f ", A[0], A[1], altA)+b.id+" "+String.format(java.util.Locale.US, "%.6f %.6f %.0f", B[0], B[1], altB);
		}
	}
}